"""HTML exporter — renders brief data as a single-page styled HTML viewer."""

from __future__ import annotations

from typing import Any

from app.export.base_exporter import BaseExporter, ExportResult


_CSS = """
body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px;
       margin: 2em auto; padding: 0 1em; color: #222; }
h1 { border-bottom: 3px solid #4A90D9; padding-bottom: .3em; }
h2 { color: #4A90D9; margin-top: 1.5em; }
.meta { color: #666; font-size: .9em; margin-bottom: 1.5em; }
.hook { background: #f0f4ff; padding: .6em 1em; border-left: 4px solid #4A90D9;
        margin: .5em 0; border-radius: 4px; }
.angle { padding: .4em 0; }
.scene { background: #fafafa; padding: .8em; margin: .5em 0; border-radius: 4px; }
.ref { display: inline-block; background: #e8f5e9; padding: .2em .6em;
       border-radius: 12px; margin: .2em; font-size: .85em; }
footer { border-top: 1px solid #ddd; margin-top: 2em; padding-top: 1em;
         color: #999; font-size: .8em; }
""".strip()


def _esc(text: str) -> str:
    """Minimal HTML escaping."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


class HtmlExporter(BaseExporter):
    """Export briefs as single-page styled HTML."""

    format_name = "html"

    def export(self, brief_data: dict[str, Any], output_path: str) -> ExportResult:
        """Render brief data to an HTML file."""
        path = self._ensure_dir(f"{output_path}.html")
        parts: list[str] = []

        title = _esc(self._safe_get(brief_data, "title", "Creative Brief"))
        parts.append("<!DOCTYPE html><html><head><meta charset='utf-8'>")
        parts.append(f"<title>{title}</title><style>{_CSS}</style></head><body>")
        parts.append(f"<h1>{title}</h1>")

        # Metadata
        meta_parts: list[str] = []
        ws = self._safe_get(brief_data, "workspace_id")
        if ws:
            meta_parts.append(f"Workspace: {_esc(ws)}")
        rid = self._safe_get(brief_data, "run_id")
        if rid:
            meta_parts.append(f"Run: {_esc(rid)}")
        if meta_parts:
            parts.append(f"<div class='meta'>{' | '.join(meta_parts)}</div>")

        # Overview
        overview = self._safe_get(brief_data, "overview")
        if overview:
            parts.append(f"<h2>Overview</h2><p>{_esc(overview)}</p>")

        # Hooks
        hooks = self._safe_get(brief_data, "hooks", [])
        if hooks:
            parts.append("<h2>Top Hooks</h2>")
            for hook in hooks:
                text = _esc(hook.get("text", hook) if isinstance(hook, dict) else hook)
                parts.append(f"<div class='hook'>{text}</div>")

        # Angles
        angles = self._safe_get(brief_data, "angles", [])
        if angles:
            parts.append("<h2>Content Angles</h2>")
            for angle in angles:
                if isinstance(angle, dict):
                    parts.append(
                        f"<div class='angle'><strong>{_esc(angle.get('name', ''))}</strong>: "
                        f"{_esc(angle.get('description', ''))}</div>"
                    )
                else:
                    parts.append(f"<div class='angle'>{_esc(str(angle))}</div>")

        # Scripts
        scripts = self._safe_get(brief_data, "scripts", [])
        if scripts:
            parts.append("<h2>Scripts</h2>")
            for idx, script in enumerate(scripts, 1):
                if isinstance(script, dict):
                    parts.append(f"<h3>Script {idx}</h3>")
                    for scene in script.get("scenes", []):
                        sn = scene.get("scene_number", idx)
                        parts.append(
                            f"<div class='scene'><strong>Scene {sn}</strong><br>"
                            f"Dialogue: {_esc(scene.get('dialogue', ''))}<br>"
                            f"Visual: {_esc(scene.get('visual_direction', ''))}</div>"
                        )

        # References
        refs = self._safe_get(brief_data, "references", [])
        if refs:
            parts.append("<h2>References</h2>")
            for ref in refs:
                if isinstance(ref, dict):
                    parts.append(f"<span class='ref'>{_esc(ref.get('title', ''))}</span>")
                else:
                    parts.append(f"<span class='ref'>{_esc(str(ref))}</span>")

        parts.append("<footer>Generated by Creative Intelligence OS</footer>")
        parts.append("</body></html>")

        content = "\n".join(parts)
        path.write_text(content, encoding="utf-8")

        return ExportResult(
            format="html",
            output_path=str(path),
            file_size_bytes=len(content.encode()),
        )
