"""Markdown exporter — renders brief data as a styled Markdown document."""

from __future__ import annotations

from typing import Any

from app.export.base_exporter import BaseExporter, ExportResult


class MarkdownExporter(BaseExporter):
    """Export briefs as Markdown (.md) files."""

    format_name = "markdown"

    def export(self, brief_data: dict[str, Any], output_path: str) -> ExportResult:
        """Render brief data to a Markdown file."""
        path = self._ensure_dir(f"{output_path}.md")
        lines: list[str] = []

        # Title
        title = self._safe_get(brief_data, "title", "Creative Brief")
        lines.append(f"# {title}\n")

        # Metadata
        workspace = self._safe_get(brief_data, "workspace_id")
        if workspace:
            lines.append(f"**Workspace:** {workspace}  ")
        run_id = self._safe_get(brief_data, "run_id")
        if run_id:
            lines.append(f"**Run ID:** {run_id}  ")
        lines.append("")

        # Overview
        overview = self._safe_get(brief_data, "overview")
        if overview:
            lines.append("## Overview\n")
            lines.append(f"{overview}\n")

        # Hooks
        hooks = self._safe_get(brief_data, "hooks", [])
        if hooks:
            lines.append("## Top Hooks\n")
            for i, hook in enumerate(hooks, 1):
                if isinstance(hook, dict):
                    lines.append(f"{i}. **{hook.get('text', '')}**")
                    if hook.get("score"):
                        lines.append(f"   - Score: {hook['score']}")
                else:
                    lines.append(f"{i}. {hook}")
            lines.append("")

        # Angles
        angles = self._safe_get(brief_data, "angles", [])
        if angles:
            lines.append("## Content Angles\n")
            for angle in angles:
                if isinstance(angle, dict):
                    lines.append(f"- **{angle.get('name', '')}**: {angle.get('description', '')}")
                else:
                    lines.append(f"- {angle}")
            lines.append("")

        # Scripts
        scripts = self._safe_get(brief_data, "scripts", [])
        if scripts:
            lines.append("## Scripts\n")
            for idx, script in enumerate(scripts, 1):
                if isinstance(script, dict):
                    lines.append(f"### Script {idx}: {script.get('hook', '')}\n")
                    for scene in script.get("scenes", []):
                        lines.append(f"**Scene {scene.get('scene_number', idx)}** "
                                     f"({scene.get('scene_type', 'body')})")
                        lines.append(f"- Dialogue: {scene.get('dialogue', '')}")
                        lines.append(f"- Visual: {scene.get('visual_direction', '')}")
                        lines.append("")
                else:
                    lines.append(f"- {script}")
            lines.append("")

        # Brand voice
        brand_voice = self._safe_get(brief_data, "brand_voice")
        if brand_voice:
            lines.append("## Brand Voice\n")
            if isinstance(brand_voice, dict):
                for k, v in brand_voice.items():
                    lines.append(f"- **{k}**: {v}")
            else:
                lines.append(str(brand_voice))
            lines.append("")

        # References
        references = self._safe_get(brief_data, "references", [])
        if references:
            lines.append("## Cultural References\n")
            for ref in references:
                if isinstance(ref, dict):
                    lines.append(f"- {ref.get('title', '')} "
                                 f"({ref.get('reference_type', '')})")
                else:
                    lines.append(f"- {ref}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by Creative Intelligence OS*\n")

        content = "\n".join(lines)
        path.write_text(content, encoding="utf-8")

        return ExportResult(
            format="markdown",
            output_path=str(path),
            file_size_bytes=len(content.encode()),
        )
