"""Tests for white-labeling support (U-17)."""

from __future__ import annotations

import pytest
from app.core.white_label import WhiteLabelConfig, WhiteLabelRegistry


class TestWhiteLabelConfig:
    def test_defaults(self):
        c = WhiteLabelConfig(workspace_id="ws1")
        assert c.primary_color == "#4A90D9"
        assert not c.has_custom_branding()

    def test_has_custom_branding(self):
        c = WhiteLabelConfig(workspace_id="ws1", agency_name="My Agency")
        assert c.has_custom_branding()

    def test_custom_domain(self):
        c = WhiteLabelConfig(workspace_id="ws1", custom_domain="app.myagency.com")
        assert c.has_custom_branding()


class TestWhiteLabelRegistry:
    def test_set_and_get(self):
        reg = WhiteLabelRegistry()
        config = WhiteLabelConfig(workspace_id="ws1", agency_name="Acme Agency")
        reg.set_config(config)
        retrieved = reg.get_config("ws1")
        assert retrieved.agency_name == "Acme Agency"

    def test_get_default(self):
        reg = WhiteLabelRegistry()
        config = reg.get_config("unknown")
        assert config.workspace_id == "unknown"
        assert config.agency_name == ""

    def test_has_config(self):
        reg = WhiteLabelRegistry()
        assert not reg.has_config("ws1")
        reg.set_config(WhiteLabelConfig(workspace_id="ws1", agency_name="Test"))
        assert reg.has_config("ws1")

    def test_apply_to_export(self):
        reg = WhiteLabelRegistry()
        reg.set_config(WhiteLabelConfig(
            workspace_id="ws1", agency_name="Acme",
            logo_url="https://acme.com/logo.png",
        ))
        data = {"title": "Brief", "footer": "Generated by Creative Intelligence OS"}
        result = reg.apply_to_export("ws1", data)
        assert result["branding"]["name"] == "Acme"
        assert result["branding"]["logo_url"] == "https://acme.com/logo.png"
        assert "Acme" in result["footer"]

    def test_apply_no_branding(self):
        reg = WhiteLabelRegistry()
        data = {"title": "Brief"}
        result = reg.apply_to_export("ws1", data)
        assert "branding" not in result

    def test_css_overrides(self):
        reg = WhiteLabelRegistry()
        reg.set_config(WhiteLabelConfig(
            workspace_id="ws1", primary_color="#FF0000",
        ))
        css = reg.get_css_overrides("ws1")
        assert "#FF0000" in css
        assert "--primary" in css

    def test_remove_config(self):
        reg = WhiteLabelRegistry()
        reg.set_config(WhiteLabelConfig(workspace_id="ws1", agency_name="Test"))
        assert reg.remove_config("ws1")
        assert not reg.has_config("ws1")

    def test_remove_nonexistent(self):
        reg = WhiteLabelRegistry()
        assert not reg.remove_config("ws1")
